let dummyData  = [
     {
         "id": 38,
         "userId": "ngzKQqzfHuNX7URTxfCesAyngoTB4r",
         "firstName": "Yaekob",
         "lastName": "BRHANE",
         "middleName": "Beyene",
         "email": "yaekob@unical.it",
         "phoneNumber": "55484848",
         "userType": "Administrative",
         "userStatus": "NotVerified",
         "department": "Telecommunication",
         "websiteLink": null,
         "address": "ENDATMKET KEBELLE 03",
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 1
     },
     {
         "id": 37,
         "userId": "RIwUdpwDBAP9PgdA3dnJFC8LyPqW0y",
         "firstName": "Yibrah",
         "lastName": "G/her",
         "middleName": "Mehari",
         "email": "yibrah@unical.it",
         "phoneNumber": "3511111111",
         "userType": "Student",
         "userStatus": "NotVerified",
         "department": "Telecommunication",
         "websiteLink": null,
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 36,
         "userId": "6yq2e9Qeyq7IaB7GS8sB7RRC4sU6ug",
         "firstName": "Naod",
         "lastName": "Brhane",
         "middleName": "Gebrehiwot",
         "email": "naodgh@unical.it",
         "phoneNumber": "3511141072",
         "userType": "Faculty",
         "userStatus": "NotVerified",
         "department": "DeMACS",
         "websiteLink": "www.naodgh.com",
         "address": "CUBO 30B MT10",
         "linkedIn": "www.linkedin.com/naod-gh",
         "twitter": "www.twitter.com/naod.gh",
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 35,
         "userId": "QZ53RxXjFp6ET6lOPAuD6w8RVKbZTb",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretammmmmjjjoooommooa@student.unicali.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": "wertyui",
         "linkedIn": "wertyuio",
         "twitter": "wertyui",
         "departmentWebsite": "ertyui",
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 34,
         "userId": "jJeMZybKnQnCO30RJg5JFnUxqLhYNU",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretammma@unical.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 33,
         "userId": "urGdqkNZcZA5BNWKvcNRJjX0eOnHDC",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretammmmmooooooa@unicali.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 32,
         "userId": "z7zXOTbpW3RIi33aPfNpVzqJPmjfrX",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "brhrlg96e30z315r@studenti.unical.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 31,
         "userId": "GM66VOJi2BdCRTPvub6IUTGFUg2y5Z",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretamjjjmmmma@gmail.unicali.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 30,
         "userId": "R8mRmPA32BivMnj5oAy05DAOH7YmU2",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretammmmma@gmail.unicali.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "NotVerified",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 29,
         "userId": "RdMOrYd8GisHWdQjpNhLeYKwQpWweq",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "ywhybb96l26z315a@studenti.unical.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "Active",
         "department": "CSE",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 28,
         "userId": "g3Ka8eyCu4nSdElDKzIqRaPEokVFpr",
         "firstName": "Robel",
         "lastName": "Brhane",
         "middleName": "Gerbrehiwot",
         "email": "robel@unical.it",
         "phoneNumber": "3511141072",
         "userType": "Student",
         "userStatus": "NotVerified",
         "department": "Telecommunication",
         "websiteLink": null,
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 23,
         "userId": "H0CZnhOB30v1pyOGMv5kSMSAC11QVh",
         "firstName": "Gourge",
         "lastName": "Teamratggg",
         "middleName": "Gideymmm",
         "email": "bretama@unical.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "Active",
         "department": "Chemistry",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     },
     {
         "id": 22,
         "userId": "I6v510MmSDMC0KFpymSrNjP7MCkDXp",
         "firstName": "Robel",
         "lastName": "Brhane",
         "middleName": "Gebrehiwot",
         "email": "robelgh@unical.it",
         "phoneNumber": "0960439375",
         "userType": "Admin",
         "userStatus": "Active",
         "department": "DeMACS",
         "websiteLink": "websiteLink",
         "address": null,
         "linkedIn": null,
         "twitter": null,
         "departmentWebsite": null,
         "departmentResponseModel": {
             "departmentId": 1,
             "departmentName": "mmmmmmmmm",
             "departmentLink": "qwertyuiomgggggggggggmmmm",
             "createdBy": null,
             "totalPage": null
         },
         "totalPages": 0
     }
 ]
    
export default dummyData